project:
  type: website

website:
  favicon: images/picpay_logo.png
  title: ""
  search: true
  navbar:
    logo: images/picpay_navbar_logo.png
    left:
      - href: index.qmd
        text: Página inicial
      - text: Bases utilizadas
        menu:
          - href: index.qmd
            text: Base sem tratamento
          - href: index.qmd
            text: Base com tratamento
          - href: index.qmd
            text: Base Final
      - text: Sobre mim
        menu:
          - href: index.qmd
            text: Quem sou eu?
          - href: index.qmd
            text: Currículo
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: 'Introdução'
        href: index.qmd
      - section: 'Etapas'
        contents:
          - href: abas/01_estrutura_do_projeto.qmd
            text: "01 - Estrutura do Projeto"
          - href: abas/02_analise_geral_do_publico.qmd
            text: "02 - Análise geral do público"
          - href: abas/03_tratamento_das_variaveis.qmd
            text: "03 - Tratamento das variáveis"
          - href: abas/04_selecao_de_variaveis.qmd
            text: "04 - Seleção de variáveis"
          - href: abas/05_treinamento_do_modelo.qmd
            text: "05 - Treinamento do modelo"
          - href: abas/06_tunning_de_hiperparametros.qmd
            text: "06 - Tunning de hiperparâmetros"
          - href: abas/07_avaliacao_final.qmd
            text: "07 - Avaliação Final"
          - href: abas/08_conclusao.qmd
            text: "08 - Conclusão"
  page-footer:
    left: "© 2025, Cedaro Enrico" 
    right:
      - icon: github
        href: https://github.com/gustavo-pradela
      - icon: linkedin
        href: https://www.linkedin.com/in/enricocedaro/

format:
  html:
    theme: flatly
    css: styles.css
    echo: false
    toc: true
    toc-depth: 3 # Define até qual nível de heading (H3) o índice irá
    toc-title: "Nesta Página"